# Generated by Django 2.2.5 on 2019-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_club', '0003_auto_20190928_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='photo_club.Tag'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
