# Generated by Django 2.2.5 on 2019-10-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_club', '0006_remove_photo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
