# Generated by Django 2.2.5 on 2019-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_club', '0009_auto_20191001_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
